[package]
name = "worship_viewer"
version = "0.1.0"
authors = ["Xilefmusics <xilefmusics@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.16"
rocket = "0.4.7"
rocket_contrib = "0.4.7"
