mod collections;
mod editor;
mod imprint;
mod index;
mod login;
mod logout;
mod player;
mod privacy;
mod setlist_editor;
mod setlists;
mod songs;
mod terms;

pub use collections::CollectionsPage;
pub use editor::EditorPage;
pub use imprint::ImprintPage;
pub use index::IndexPage;
pub use login::LoginPage;
pub use logout::LogoutPage;
pub use player::PlayerPage;
pub use privacy::PrivacyPage;
pub use setlist_editor::SetlistEditorPage;
pub use setlists::SetlistsPage;
pub use songs::SongsPage;
pub use terms::TermsPage;
