mod collections;
mod editor;
mod index;
mod login;
mod logout;
mod player;
mod presenter;
mod presenter_slides;
mod setlist_editor;
mod setlists;
mod songs;

pub use collections::CollectionsPage;
pub use editor::EditorPage;
pub use index::IndexPage;
pub use login::LoginPage;
pub use logout::LogoutPage;
pub use player::PlayerPage;
pub use presenter::PresenterPage;
pub use presenter_slides::PresenterSlidesPage;
pub use setlist_editor::SetlistEditorPage;
pub use setlists::SetlistsPage;
pub use songs::SongsPage;
